//
// auto-generated by op2.py
//

#ifdef _OPENMP
  #include <omp.h>
#endif

#include "user_openmp.h"
// global constants

// header
#include "op_lib_cpp.h"

// user kernel files
#include "rhscal_auxsideflux_kernel.cpp"
#include "rhscal_auxsideflux2_kernel.cpp"
#include "rhscal_auxvar_kernel.cpp"
#include "rhscal_calsideflux_kernel.cpp"
#include "rhscal_calsideflux2_kernel.cpp"
#include "rhscal_kernel.cpp"
