//
// auto-generated by op2.py
//

//user function
inline void recons_1wh(uvar *pvar)
{
		unsigned int pdg    = (*pvar).pdg;
		unsigned int pfv    = (*pvar).pfv;
		unsigned int ndgdof = DOFofOrd2d[pdg];
		unsigned int nfvdof = DOFofOrd2d[pfv];
		
		for( unsigned int i=0; i<ndgdof; i++ )
		for( unsigned int j=0; j<NEQ;    j++ )
			(*pvar).wh[i][j] = (*pvar).uh[1][i][j];

		for( unsigned int i=ndgdof; i<nfvdof; i++ )
		for( unsigned int j=0; j<NEQ;         j++ )
			(*pvar).wh[i][j] = 0.0;
}




// host stub function
void op_par_loop_recons_1wh(char const *name, op_set set,
  op_arg arg0){

  int nargs = 1;
  op_arg args[1];

  args[0] = arg0;
  //create aligned pointers for dats
  ALIGNED_uvar       uvar * __restrict__ ptr0 = (uvar *) arg0.data;
  DECLARE_PTR_ALIGNED(ptr0,uvar_ALIGN);

  // initialise timers
  double cpu_t1, cpu_t2, wall_t1, wall_t2;
  op_timing_realloc(2);
  op_timers_core(&cpu_t1, &wall_t1);


  if (OP_diags>2) {
    printf(" kernel routine w/o indirection:  recons_1wh");
  }

  int exec_size = op_mpi_halo_exchanges(set, nargs, args);

  if (exec_size >0) {

    #ifdef VECTORIZE
    #pragma novector
    for ( int n=0; n<(exec_size/SIMD_VEC)*SIMD_VEC; n+=SIMD_VEC ){
      #pragma omp simd simdlen(SIMD_VEC)
      for ( int i=0; i<SIMD_VEC; i++ ){
        recons_1wh(
          &(ptr0)[1 * (n+i)]);
      }
    }
    //remainder
    for ( int n=(exec_size/SIMD_VEC)*SIMD_VEC; n<exec_size; n++ ){
    #else
    for ( int n=0; n<exec_size; n++ ){
    #endif
      recons_1wh(
        &(ptr0)[1*n]);
    }
  }

  // combine reduction data
  op_mpi_set_dirtybit(nargs, args);

  // update kernel record
  op_timers_core(&cpu_t2, &wall_t2);
  OP_kernels[2].name      = name;
  OP_kernels[2].count    += 1;
  OP_kernels[2].time     += wall_t2 - wall_t1;
  OP_kernels[2].transfer += (float)set->size * arg0.size * 2.0f;
}
