//
// auto-generated by op2.py
//

#include "user_cuda.h"
//global constants
#ifndef MAX_CONST_SIZE
#define MAX_CONST_SIZE 2500
#endif


//header
#include "op_lib_cpp.h"
#include "op_cuda_rt_support.h"
#include "op_cuda_reduction.h"

void op_decl_const_char(int dim, char const *type,
int size, char *dat, char const *name){
  if (!OP_hybrid_gpu) return;
  {
    printf("error: unknown const name\n"); exit(1);
  }
}

//user kernel files
#include "rhscal_auxsideflux_kernel.cu"
#include "rhscal_auxsideflux2_kernel.cu"
#include "rhscal_auxvar_kernel.cu"
#include "rhscal_calsideflux_kernel.cu"
#include "rhscal_calsideflux2_kernel.cu"
#include "rhscal_kernel.cu"
