//
// auto-generated by op2.py
//

#include "user_genseq.h"
// global constants

// header
#include "op_lib_cpp.h"

// user kernel files
#include "rhscal_auxsideflux_seqkernel.cpp"
#include "rhscal_auxsideflux2_seqkernel.cpp"
#include "rhscal_auxvar_seqkernel.cpp"
#include "rhscal_calsideflux_seqkernel.cpp"
#include "rhscal_calsideflux2_seqkernel.cpp"
#include "rhscal_seqkernel.cpp"
